### ISSUE TITLE
Extract durations from the trained model

### ISSUE THREAD

**Issue by adnan-mehremic** [janvainer/speedyspeech#16]
Hi, I tried to train this model/repo on AWS, and on the third step (Extract durations from the trained model - creates alignments.txt file in the LJSpeech-1.1 folder) I got this error. May you help me, please?

_I used: AWS image Deep Learning AMI (Ubuntu 18.04) Version 36.0_

```
ubuntu@ip-172-31-68-24:~/speedyspeech$ python code/extract_durations.py logs/2020-11-17T10-20-06-/events.out.tfevents.1605608406.ip-172-31-68-24.3394.0 code/datasets/data/LJSpeech-1.1     --durations_filename my_durations.txt
Model sent to cuda
Traceback (most recent call last):
  File "code/extract_durations.py", line 161, in <module>
    m = DurationExtractor().load(args.checkpoint)
  File "/home/ubuntu/speedyspeech/code/duration_extractor.py", line 233, in load
    checkpoint = torch.load(checkpoint)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x18'.
```

**Comment by adnan-mehremic** [comment]
Also, I had this error during installation requirement file, and I removed this line "pkg-resources==0.0.0"

```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.                                                      0.0 (from -r requirements.txt (line 34)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirem                                                      ents.txt (line 34))
```

**Comment by adnan-mehremic** [comment]
> Also, I had this error during the installation requirement file, and I removed this line "pkg-resources==0.0.0"
> Is it ok?
> 
> ```
> ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 34)) (from versions: none)
> ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 34))
> ```

SOLVED with:
` pip freeze | grep -v "pkg-resources" > requirements.txt`

**Comment by janvainer** [comment]
Hi, good catch with the requirements file bug. The pkg-resources is an ubuntu bug. I will remove the dependency soon.
Did you use your own data for your experiments? It seems like you are trying to load a file with nonstandard text encoding.

**Comment by adnan-mehremic** [comment]
> Hi, good catch with the requirements file bug. The pkg-resources is an ubuntu bug. I will remove the dependency soon.
> Did you use your own data for your experiments? It seems like you are trying to load a file with nonstandard text encoding.

Thx for the response. 
I used everything listed in the Training steps, from downloading LJSpeech-1.1 to this step where I had an error. I followed your repo instructions.

**Comment by janvainer** [comment]
Is this your checkpoint for the duration predictor?: `logs/2020-11-17T10-20-06-/events.out.tfevents.1605608406.ip-172-31-68-24.3394.0`. What format is it? It seems like a tensorboard log and not like a model checkpoint

**Comment by adnan-mehremic** [comment]
> Is this your checkpoint for the duration predictor?: `logs/2020-11-17T10-20-06-/events.out.tfevents.1605608406.ip-172-31-68-24.3394.0`. What format is it? It seems like a tensorboard log and not like a model checkpoint

Yes, it is. I got it after I run a step before
`python code/duration_extractor.py  with 5 epochs`

**Comment by janvainer** [comment]
I think the file you are using is a tensorboard log file. The checkpoints created by duration predictor have the following format:
```
{log_dir}/{time.strftime("%Y-%m-%d")}checkpoint_step{step}.pth'
```
For example `logs/2020-11-17checkpoint_step1000.pth` should be a valid checkpoint. Try to take a look if there is a *.pth file in your logs directory.
`
You can check for yourself in the [code](https://github.com/janvainer/speedyspeech/blob/8a6c42b8812b64b2c44a2a0b6766d284f7269824/code/duration_extractor.py#L220).

**Comment by adnan-mehremic** [comment]
Unfortunately, I don't have that file with the extension .pth in my logs directory. I didn't change anything into your code. Do you know what could be a problem?

**Comment by janvainer** [comment]
Ok this could be the problem. You trained the model for 5 epochs, right? First of all, this will definitely be not enough. Secondly, the chekcpointing happens every 10 epochs as can be seen [here](https://github.com/janvainer/speedyspeech/blob/8a6c42b8812b64b2c44a2a0b6766d284f7269824/code/duration_extractor.py#L533). So in your case, no checkpoint was saved. Train for the default number of epochs to get some results :). Let me know if this helps

**Comment by janvainer** [comment]
Closing for inactivity. Feel free to re-open
